/// DropType
///
/// Domain model representing a liquid drop type for dosing pumps.
///
/// Based on reef-b-app entity DropType.kt.
class DropType {
  final int id;
  final String name;
  final bool isPreset;

  const DropType({
    required this.id,
    required this.name,
    required this.isPreset,
  });

  /// Creates a new DropType with auto-generated ID (for insertion).
  factory DropType.create({
    required String name,
    bool isPreset = false,
  }) {
    return DropType(
      id: 0, // Will be auto-generated by database
      name: name,
      isPreset: isPreset,
    );
  }

  /// Creates a copy with updated fields.
  DropType copyWith({
    int? id,
    String? name,
    bool? isPreset,
  }) {
    return DropType(
      id: id ?? this.id,
      name: name ?? this.name,
      isPreset: isPreset ?? this.isPreset,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DropType &&
          other.id == id &&
          other.name == name &&
          other.isPreset == isPreset;

  @override
  int get hashCode => Object.hash(id, name, isPreset);

  @override
  String toString() =>
      'DropType(id: $id, name: $name, isPreset: $isPreset)';
}

